# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR_REPORT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRIME_TYPE', models.CharField(max_length=100)),
                ('LOCATION_LAT', models.IntegerField()),
                ('LOCATION_LONG', models.IntegerField()),
                ('CRIME_DESCRIPTION', models.CharField(max_length=1000)),
                ('COMPLAINT_BY', models.CharField(max_length=100)),
                ('DATE_CRIME', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('TIME_CRIME', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('FIR_LOC', models.CharField(max_length=100)),
                ('COMPLAINT_TIME', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('PHONE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USER_REF', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='USER', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('NAME', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='fir_report',
            name='PERSON_COMPLAINT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeReporting.USER'),
        ),
    ]
