# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0002_auto_20180314_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir_report',
            old_name='LOCATION_LAT',
            new_name='LAT',
        ),
        migrations.RenameField(
            model_name='fir_report',
            old_name='LOCATION_LONG',
            new_name='LONG',
        ),
        migrations.RenameField(
            model_name='fir_report',
            old_name='STATUS_OF_CRIME',
            new_name='STATUS',
        ),
    ]
