# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0003_auto_20180314_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir_report',
            old_name='LONG',
            new_name='LNG',
        ),
    ]
