# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0004_auto_20180314_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir_report',
            name='STATUS',
            field=models.CharField(choices=[(b'pending', b'PENDING'), (b'moved', b'MOVED TO COURT'), (b'closed', b'CLOSED')], default=b'Pending', max_length=100),
        ),
    ]
