# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0004_auto_20180314_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir_report',
            name='COMPLAINT_TIME',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='DATE_CRIME',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='TIME_CRIME',
            field=models.TimeField(),
        ),
    ]
