# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 16:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0004_auto_20180316_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_timeline',
            name='TIME_OF_UPDATE',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 17, 16, 46, 33, 214763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='COMPLAINT_TIME',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='DATE_CRIME',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='TIME_CRIME',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_REF',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='USER_REF', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
