# Generated by Django 2.0.2 on 2018-03-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0005_auto_20180315_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir_report',
            name='STATUS',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
