# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0005_auto_20180315_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRIME_TIMELINE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURRENT_STATUS', models.CharField(choices=[('lodged', 'LODGED'), ('pending', 'PENDING'), ('investigated', 'INVESTIGATED'), ('evidence_collection', 'EVIDENCE COLLECTION'), ('moved', 'MOVED TO COURT'), ('closed', 'CLOSED')], default='Pending', max_length=100)),
                ('TIME_OF_UPDATE', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='STATUS',
            field=models.CharField(choices=[('lodged', 'LODGED'), ('pending', 'PENDING'), ('investigated', 'INVESTIGATED'), ('evidence_collection', 'EVIDENCE COLLECTION'), ('moved', 'MOVED TO COURT'), ('closed', 'CLOSED')], default='Lodged', max_length=100),
        ),
        migrations.AddField(
            model_name='crime_timeline',
            name='CRIME_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeReporting.FIR_REPORT'),
        ),
        migrations.AddField(
            model_name='crime_timeline',
            name='UPDATED_BY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeReporting.USER'),
        ),
    ]
