# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0005_auto_20180317_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_timeline',
            name='TIME_OF_UPDATE',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 17, 16, 57, 47, 266464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='crime_timeline',
            name='UPDATED_BY',
            field=models.ForeignKey(db_column='NAME', on_delete=django.db.models.deletion.CASCADE, to='crimeReporting.USER'),
        ),
    ]
