# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 08:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0006_auto_20180317_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='PASSWORD',
        ),
        migrations.AlterField(
            model_name='crime_timeline',
            name='TIME_OF_UPDATE',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 18, 8, 41, 50, 657998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_REF',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='USER', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
