# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0007_auto_20180318_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_timeline',
            name='TIME_OF_UPDATE',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 18, 8, 54, 23, 585630, tzinfo=utc)),
        ),
    ]
