# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0008_auto_20180318_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='INFORMATION_FILING_APP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aadharcard', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('crimetype', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('crime_description', models.CharField(max_length=100)),
                ('date_crime', models.DateField()),
                ('time_crime', models.TimeField()),
                ('complaint_time', models.TimeField()),
                ('complaint_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='fir_report',
            name='COMPLAINT_DATE',
            field=models.DateField(default=datetime.datetime(2018, 3, 22, 15, 46, 3, 595695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='crime_timeline',
            name='TIME_OF_UPDATE',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 22, 15, 46, 3, 599695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='COMPLAINT_TIME',
            field=models.TimeField(default=datetime.datetime(2018, 3, 22, 15, 46, 3, 595695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='PERSON_COMPLAINT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimeReporting.USER'),
        ),
    ]
