# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0011_auto_20180323_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INFORMATION_FILING_APP',
        ),
        migrations.AlterField(
            model_name='crime_timeline',
            name='TIME_OF_UPDATE',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 23, 18, 16, 44, 448385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='COMPLAINT_DATE',
            field=models.DateField(default=datetime.datetime(2018, 3, 23, 18, 16, 44, 446385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='COMPLAINT_TIME',
            field=models.TimeField(default=datetime.datetime(2018, 3, 23, 18, 16, 44, 446385, tzinfo=utc)),
        ),
    ]
