# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0016_auto_20180325_0902'),
        ('crimeReporting', '0015_auto_20180326_2023'),
    ]

    operations = [
    ]
