# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crimeReporting', '0018_auto_20180328_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='POLICE_STATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POLICE_STATION_LAT', models.FloatField()),
                ('POLICE_STATION_LNG', models.FloatField()),
                ('POLICE_ADDRESS', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='crime_timeline',
            name='TIME_OF_UPDATE',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 30, 7, 17, 30, 10551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='COMPLAINT_DATE',
            field=models.DateField(default=datetime.datetime(2018, 3, 30, 7, 17, 30, 8551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fir_report',
            name='COMPLAINT_TIME',
            field=models.TimeField(default=datetime.datetime(2018, 3, 30, 7, 17, 30, 8551, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='LAT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LAT', to='crimeReporting.POLICE_STATION'),
        ),
        migrations.AddField(
            model_name='user',
            name='LNG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LNG', to='crimeReporting.POLICE_STATION'),
        ),
    ]
